### ISSUE TITLE
Notification key secrecy

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#11]
Is there any good reason to keep `notification_key` secret? 

In my understanding:
* it should not be hard to bruteforce it from a picture of a QR_entry code;
* the `notification_key` does not offer new capabilities compared to having a picture of the QR_entry code

**Comment by wouterl** [comment]
Please group requests for clarifications rather than making new issues for each question.

As explained in the QR code generation section:

> The notification key notification_key is used to encode messages by the health authority so that they can only be decrypted by apps of users that actually visited the corresponding location. This protection is not perfect. Anybody that knows or learns notification_key can subsequently make it public.

Thus, if you have the code (or a photo) you don’t need to bruteforce, just read it. The secrecy of this key is not crucial for abuse prevention or privacy of the users. It is designed to protect the content of messages sent by the health authorities to ensure, to the extent possible, that only visitors can read them. As the document points out, this is not a secrecy guarantee, anybody that learns this key can publish the message or the key itself. Yet, it provides a layer of security for most of the cases.

**Comment by pdehaye** [comment]
I had seen that section as well, but still could not make sense of the whole thing (hence why in my mind that was two different questions_. Even the non-secrecy guarantee in the text was not as helpful as could have been. May I suggest adding one line in the text akin to "scanning the QR code amounts to learning the notification_key"?

**Comment by carmelatroncoso** [comment]
Sure, thanks.
