### ISSUE TITLE
Why not use DH shared secret directly to encrypt c ?

### ISSUE THREAD

**Issue by agreulich** [CrowdNotifier/documents#31]
First - congratulations, this is a very nice design, and I like the way you apply DH, sharing over the timeline instead of between 2 parties. 

One thing I don't get, maybe I'm missing something? At entry, a visitor stores

```(g^r , pk^r , Enc(pk, ...))```

as `(h, k, c)` triple, so his own public key, the shared secret (actually rather used as a matcher than a secret here), and context encrypted with the location public key. Why not instead storing just the pair

```(g^r , Enc(pk^r, ...))```

So, use the shared secret directly as encryption key, and not just as a matcher, and not store the shared secret itself at all? At notification time, when `sk` of the venue is distributed, the visitor calculates (same as now) the presumed shared secret for each of his records `h^sk = g^r^sk`, which would be equal to pk^r in case of a match, then just tries to use this as decryption key for `c` (which of course must then contain some kind of checksum). Yes, it would need additional CPU time to try the symmetric decryption, but if a validation data block (containing some random data plus a checksum) appears first, only this one block needs to be decrypted and the checksum verified. It should not cost much more than the `h^sk` calculation. Advantage would be that an "attacker" who knows the entry QR code (and so `pk`, which is in this QR code) AND gains access to the data stored in the smartphone (e.g. police) could not decrypt this `c` part (at least not until an actual notification occurs and `sk` becomes public), while in your design she can (because `c` is encrypted with `pk`), and she can also verify a successful decryption via `notification_key` (present also in the entry QR code and as such ready for comparison). In addition, it is really made sure that `c` is never accidentally identical for 2 visitors that check in at the same venue at the same time, because the encryption key depends on the chosen private key of the visitor(s). 

[EDIT]: One problem with my suggestion I see is how to store the exit record `Enc(pk^r, departure_time || “departure”)` (when the visitor leaves the event); the shared secret would have to still be available at this time (using time-limited caching), but I think this is a bit risky. Probably the safest approach would be to generate a new private key `r'` for the exit record, and then store `(g^r' , Enc(pk^r', departure_time || “departure”))`. Actually, it might be best to store that just as another pair (not in the same quadruple) and not make a structural difference between entry and exit records before decryption: the decrypted `c` tells you after all if this is an entry or an exit record. Care must be taken though as the stay at a venue might cross midnight (i.e. departure at the next day). 

Alternatively, a random time could be stored in the entry record, and then just the difference of the departure time to this random time (a correction value) would be stored as an additional, unencrypted value.

PS: 2 very small typo/clarifications which ar enot wortth an issue of their own, so I attach them here:

- Page 14, point 5 of "Initiating contact tracing": "notification_keys" should read just "notification_key"

- Page 14, point 2b of "Presence tracing and notification": "the app decrypts the ciphertext c using sk": it might be better to clarify "... using pk = g^sk" (kind of obvious of course), or  of course `pk^r = h^sk` if the shared key is used for encryption (but that would require rephrasing the whole paragraph anyway)

**Comment by wouterl** [comment]
Thanks @agreulich for the nice suggestion and for the typos. We fixed the first one.

The second typo, and your write-up above reveals something that we should make more clear in the whitepaper. For `Enc` we always envisioned using _asymmetric_ encryption. So that indeed, to decrypt it, you'd need the private key `sk`. This is also why an attacker knowing the QR code cannot decrypt the ciphertext, it would need `sk` (up to that point secret) not `pk`. Will clarify this. Thx.

I like the conciseness of your suggestion to use the shared secret directly as a key for the ciphertext. Rather than using a checksum, the "proper" way would be to use an authenticated encryption scheme with `pk^r` as the key. This would totally work! However, for clarity of exposition, we prefer for now to keep them separate. This is also a bit more efficient, as it avoids having to do trial decryption in addition to the group operation alone, but I will admit that the difference is small.

**Comment by agreulich** [comment]
Thanks, indeed I assumed a symmetric encryption; if it is asymmetric it's a different situation, and I'm looking forward for the clarified paper. What I currently don't understand yet is that `pk` is defined as a DH public key in step 1 (`pk = g^sk`), but should then be used in `Enc(pk, ...)` as a (say) RSA public key? As far as I know, DH can't be used in the same way as RSA (but I might be wrong, I only know it as key exchange protocol), so I assume 2 independent keypairs are used (DH and e.g. RSA), as in 2 private keys and 2 public keys? This would also require to distribute both private keys in the notification, one DH for the matching, and one RSA for the decryption. Works well of course, just want to be sure I understand the final approach. But I guess I'll see it in the paper. And I hope an actual app will be built from it, and better sooner than later :+1:

PS: One small thing to note is that this way, 2 visitors arriving at the SAME time would end with the same encrypted part (same public key and parts in the data blob). Worse, somebody knowing the public key and the `Enc(...)` part could bruteforce all possible arrival times of a day to check for a match. So, I think an additional random element - also in the departure entry - might be a good idea?

**Comment by wouterl** [comment]
We'll clarify, but the standard approach would be to use some form of ElGamal encryption, which would indeed support DH-like public keys as defined in the paper. Good point about spelling this out.

As for the PS: public key encryption (apart from text-book RSA) uses randomization so that ciphertexts are different, even if the plaintext are the same. So that would prevent the attack that you describe. For RSA things are a bit trickier (which is why textbook RSA is not so nice), but see for example RSA OAEP. It includes the idea you described of adding a random value.
